#!/bin/bash

#
# Parses all .txt files stored in the directory "in", and saves the output in the directory "out"
#

#sbt 'runMain org.clulab.habitus.variables.VariableReader -in in -out out -grammar /variables/master.yml'

sbt 'runMain org.clulab.habitus.variables.PlantingAreaReader -in /home/alexeeva/Desktop/habitus_related/data/saed-bulletins-as-of-jan28/in -out /home/alexeeva/Desktop/habitus_related/data/saed-bulletins-as-of-jan28/out -grammar /variables/master-areas.yml'


