#!/bin/bash

#
# Parses all .txt files stored in the directory "in", and saves the output in the directory "out"
#

sbt 'runMain org.clulab.habitus.variables.PlantingAreaReader' # or VariableReader for just dates