package org.clulab.habitus.scraper

import net.ruippeixotog.scalascraper.browser.Browser
import org.clulab.habitus.scraper.scrapers.Scraper

import scala.util.Try

class Corpus(val pages: Seq[Page]) {

  def download(browser: Browser, baseDirName: String): Unit = {
    pages.foreach { page =>
      val scraper = Scraper.getScraper(page)
      val downloadTry = Try(scraper.downloadTo(browser, page, baseDirName))

      if (downloadTry.isFailure)
        println(s"Download of ${page.url.toString} failed!")
    }
  }

  def scrape(browser: Browser, baseDirName: String): Unit = {
    pages.foreach { page =>
      val scraper = Scraper.getScraper(page)

      scraper.scrapeTo(browser, page, baseDirName)
    }
  }
}

object Corpus {
  val original = Seq(
    // 1.1 - 1.5
    // https://www.adomonline.com/?s=illegal+mining+galamsey
    // This first one doesn't work with the %e2%82%b5 copied and pasted directly from the browser.
    Page("https://www.adomonline.com/galamseyer-fined-\u20B51-2-billion-for-illegal-mining/"),
    Page("https://www.adomonline.com/galamsey-worsened-because-of-you-ashanti-chiefs-call-out-politicians-over-illegal-mining/"),
    Page("https://www.adomonline.com/galamsey-14-regions-devastated-by-illegal-mining-activities-dr-solomon-owusu-reveals/"),
    Page("https://www.adomonline.com/stop-illegal-mining-take-advantage-of-govts-employment-programs-okyenhene-to-galamseyers/"),
    Page("https://www.adomonline.com/chinese-galamsey-queen-still-mining-illegally-inter-ministerial-taskforce-complains/"),

    // 2.1 - 2.5
    // https://citifmonline.com/?s=galamsey
    Page("https://citifmonline.com/2018/04/three-illegal-miners-die-galamsey-pit-bekwai/"),
    Page("https://citifmonline.com/2018/03/galamsey-operator-jailed-18-months-unlawful-escape/"),
    Page("https://citifmonline.com/2018/03/5-galamseyers-mining-with-cyanide-to-face-court-today/"),
    Page("https://citifmonline.com/2018/03/shoot-kill-galamseyers-suggestion-unfortunate-aning/"),
    Page("https://citifmonline.com/2018/03/mp-kicks-against-shoot-to-kill-proposal-in-galamsey-fight/"),

    // 3.1 - 3.5
    // https://citifmonline.com/?s=galamsey+environment+farmer
    Page("https://citifmonline.com/2017/12/ngo-plants-trees-to-reclaim-destroyed-galamsey-lands/"),
    Page("https://citifmonline.com/2017/07/ghana-science-associaton-joins-galamsey-fight/"),
    Page("https://citifmonline.com/2017/05/govt-will-sustain-fight-against-galamsey-western-regional-minister/"),
    Page("https://citifmonline.com/2017/05/stop-galamsey-start-farming-peasant-farmers-advocate/"),
    Page("https://citifmonline.com/2017/04/ghanas-cocoa-risk-international-boycott-over-galamsey-minister/"),

    // 4
    // https://citifmonline.com/2018/03/gold-rush-public-health-water-bodies-article/
    Page("https://citifmonline.com/2018/03/gold-rush-public-health-water-bodies-article/"),
  )

  val extended = Seq(
    // 1.6 - 1.14
    // https://www.adomonline.com/?s=illegal+mining+galamsey
    Page("https://www.adomonline.com/well-fight-galamseyers-with-bulletproof-vest-and-weapons-abu-jinapor/"),
    Page("https://www.adomonline.com/small-scale-mining-fetched-ghana-almost-us1-2-billion-in-2022-minister/"),
    Page("https://www.adomonline.com/galamsey-i-feel-the-pains-of-ghanaians-stonebwoy/"),
    Page("https://www.adomonline.com/police-invite-frimpong-boateng-over-galamsey-report/"),
    Page("https://www.adomonline.com/galamsey-accident-nadmo-gives-update-on-remaining-trapped-miners/"),
    Page("https://www.adomonline.com/galamsey-pit-collapse-7-dead-only-5-rescued-alive-many-remain-trapped/"),
    Page("https://www.adomonline.com/babies-in-galamsey-areas-are-being-born-with-one-eye-without-genitalia-pathologist/"),
    Page("https://www.adomonline.com/galamsey-sub-chief-two-foreign-nationals-arrested-at-akyem-oda/"),
    Page("https://www.adomonline.com/galamsey-im-available-if-my-ideas-are-still-needed-prof-frimpong-boateng/"),

    // 2.6 - 2.10
    // https://citifmonline.com/?s=galamsey
    Page("https://citifmonline.com/2018/03/er-2-pupils-drown-in-galamsey-pit-at-akyem-takorase/"),
    Page("https://citifmonline.com/2018/02/galamsey-threatens-ghanas-provision-of-water-researcher/"),
    Page("https://citifmonline.com/2018/02/punishment-for-galamseyers-must-be-deterrent-enough-media-coalition/"),
    Page("https://citifmonline.com/2018/02/armed-forces-intensify-anti-galamsey-fight-on-river-bodies/"),
    Page("https://citifmonline.com/2018/01/operation-vanguard-boss-laments-slow-prosecution-of-galamseyers/"),

    // 3.6 - 3.10
    // https://citifmonline.com/?s=galamsey+environment+farmer
    Page("https://citifmonline.com/2017/04/the-wolves-in-sheeps-clothing-citi-fms-galamsey-campaign-in-retrospect/"),
    Page("https://citifmonline.com/2017/04/galamseyers-at-akrofusu-defy-governments-ultimatum/"),
    Page("https://citifmonline.com/2017/04/deport-foreign-nationals-involved-in-galamsey-group/"),
    Page("https://citifmonline.com/2017/04/govt-must-lead-efforts-to-end-galamsey-charismatic-churches/"),
    Page("https://citifmonline.com/2017/04/stopgalamseynow-selling-our-birth-right-in-the-guise-of-trade-article/"),

    // 5.1 - 5.10
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Appoint-me-as-Water-Resources-Minister-and-I-ll-end-galamsey-in-two-weeks-Chief-1777016"),
    Page("https://www.ghanaweb.com/GhanaHomePage/regional/Illegal-miners-invade-cocoa-farms-at-Asante-Bekwai-District-Cocoa-Officer-laments-1776965"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/We-need-stronger-hands-in-the-galamsey-fight-Advocate-1777313"),
    Page("https://www.ghanaweb.com/GhanaHomePage/regional/We-will-deal-harshly-with-ruthless-illegal-miners-in-Akrofuom-DCE-1777052"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Teshie-Residents-take-to-the-streets-over-dilapidated-roads-1776479"),
    Page("https://www.ghanaweb.com/GhanaHomePage/regional/Boy-12-drowns-in-abandoned-galamsey-pit-at-Denkyira-Gyaman-1774793"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Political-partisanship-greed-selfishness-making-galamsey-fight-difficult-Inusah-Fuseini-1774688"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Government-to-provide-bulletproof-vests-and-weapons-to-fight-galamseyers-Jinapor-1773986"),
    Page("https://www.ghanaweb.com/GhanaHomePage/features/Where-are-the-Nkrumahs-the-Mugabes-and-Gadafis-of-our-generation-The-menace-of-galamsey-in-Ghana-1774358"),
    Page("https://www.ghanaweb.com/GhanaHomePage/features/Are-galamseyers-and-Okada-operators-jumping-for-joy-over-Mahama-s-2024-candidacy-1773563")
  )

  // There were 45 above, so add 55 more for 100 total.

  val hundred = Seq(
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-report-Akufo-Addo-s-head-of-security-sues-Frimpong-Boateng-seeks-GH-5m-damages-1780727"),
    Page("https://www.ghanaweb.com/GhanaHomePage/regional/DCE-narrates-how-illegal-miners-attack-soldiers-in-Obuasi-1780250"),
    Page("https://www.ghanaweb.com/GhanaHomePage/regional/Operation-Halt-II-team-arrests-26-galamseyers-at-Patase-1780157"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Why-small-scale-mining-cannot-be-banned-outrightly-Martin-Ayisi-1780295"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Akufo-Addo-his-appointees-NPP-executives-are-into-galamsey-MP-alleges-1779278"),
    Page("https://www.ghanaweb.com/GhanaHomePage/business/MTN-calls-for-multi-sectorial-approach-to-fighting-MoMo-Internet-fraud-1779467"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Aluta-continua-Kweku-Baako-reacts-to-adjournment-of-case-against-Ken-Agyapong-1778576"),
    Page("https://www.ghanaweb.com/GhanaHomePage/regional/Minister-for-Sanitation-and-Water-Resources-inspects-water-treatment-plant-1778951"),
    Page("https://www.ghanaweb.com/GhanaHomePage/features/Alternative-livelihood-programs-in-solving-galamsey-Will-the-artisanal-miners-still-return-or-not-1778222"),
    // This one came in middle of first 10.
    Page("https://www.ghanaweb.com/GhanaHomePage/features/In-the-shoes-of-the-president-1777487"),

    Page("https://www.ghanaweb.com/GhanaHomePage/regional/Man-dies-in-galamsey-pit-at-Kofikurom-1773533"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Cutting-Trees-for-Galamsey-A-serious-threat-to-climate-change-and-food-security-in-the-Upper-Denkyira-East-Municipality-1772708"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Drug-traffickers-are-smart-and-sophisticated-Ghanaian-youth-need-proper-mentoring-Criminologist-1772489"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Today-at-the-newsstands-May-23-2023-1771970"),
    Page("https://www.ghanaweb.com/GhanaHomePage/features/Galamsey-A-threat-Ghana-must-abolish-1770887"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Bawumia-vs-Mahama-Apaak-Annoh-Dompreh-trade-blows-on-Twitter-1770368"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Small-scale-mining-fetched-Ghana-almost-US-1-2-billion-in-2022-Minister-1770338"),
    Page("https://www.ghanaweb.com/GhanaHomePage/business/Small-scale-mining-fetched-Ghana-almost-US-1-2-billion-in-2022-Lands-Minister-1769996"),
    Page("https://www.ghanaweb.com/GhanaHomePage/features/Thousands-of-Ghanaians-may-well-die-from-Chisso-Minamata-disease-1769957"),
    Page("https://www.ghanaweb.com/GhanaHomePage/regional/Asantehene-reiterates-commitment-to-go-for-galamsey-chiefs-1769192"),
    Page("https://www.ghanaweb.com/GhanaHomePage/crime/Charles-Bissue-s-case-Compel-OSP-to-produce-Anas-petition-Lawyers-to-court-1769237"),
    Page("https://www.ghanaweb.com/GhanaHomePage/regional/Chiefs-must-answer-to-effects-of-illegal-mining-in-their-areas-Otumfuo-1769321"),
    Page("https://www.ghanaweb.com/GhanaHomePage/features/Eye-asem-oo-It-s-no-joke-1769225"),
    Page("https://www.ghanaweb.com/GhanaHomePage/politics/NPP-should-not-elect-a-liar-as-a-candidate-Farmers-1768874"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Otumfuo-King-Charles-III-to-collaborate-to-reclaim-lands-destroyed-by-galamsey-1768946"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/I-hate-it-utterly-Historian-calls-on-Mahama-to-scrap-Council-of-State-1768538"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Editorial-by-Ghanaian-Times-Chiefs-politicians-and-security-personnel-can-stop-galamsey-1768748"),
    Page("https://www.ghanaweb.com/GhanaHomePage/regional/NADMO-confirms-the-deaths-of-seven-miners-as-a-result-of-a-pit-collapse-1768292"),
    Page("https://www.ghanaweb.com/GhanaHomePage/politics/We-believe-in-Afriyie-Akoto-not-Bawumia-Farmers-1768640"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-report-Akufo-Addo-s-firm-represents-Capt-Koda-against-Frimpong-Boateng-1767734"),

    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Police-invites-Frimpong-Boateng-over-galamsey-report-1768172"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/7-galamseyers-dead-17-trapped-in-pit-at-Birim-North-Report-1767569"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Climate-change-its-impact-on-Ghana-s-cocoa-production-and-the-way-forward-1767320"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/FULL-SPEECH-Mahama-s-post-presidential-primaries-acceptance-speech-1767497"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Today-at-the-newsstands-Mahama-s-primary-victory-dominates-May-15-2023-headlines-1767062"),
    Page("https://www.ghanaweb.com/GhanaHomePage/features/Attorney-General-Godfred-Dame-and-Paul-Adom-Otchere-responsible-for-illegal-mining-1766378"),
    Page("https://www.ghanaweb.com/GhanaHomePage/features/From-live-leopard-to-live-deer-1766306"),
    Page("https://www.ghanaweb.com/GhanaHomePage/entertainment/Stonebwoy-launches-borehole-project-to-empower-communities-through-access-to-clean-water-1766468"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/But-for-national-dialogue-galamsey-would-ve-been-worse-Akufo-Addo-1765361"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-report-not-whole-compilation-of-Frimpong-Boateng-s-views-on-certain-issues-AG-1765307"),
    Page("https://www.ghanaweb.com/GhanaHomePage/regional/Galamsey-Large-quantities-of-heavy-metals-discovered-in-women-wombs-Pathologist-1765598"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Illegal-small-scale-mining-poses-threat-to-our-very-survival-Akufo-Addo-1765313"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Inducement-offers-and-death-threats-Godfred-Dame-shares-challenges-of-being-Attorney-General-1765358"),
    Page("https://www.ghanaweb.com/GhanaHomePage/features/We-are-waiting-for-Dr-Bawumia-1765688"),
    Page("https://www.ghanaweb.com/GhanaHomePage/regional/8-407-malaria-cases-recorded-in-the-Upper-Denkyira-East-Municipality-1764209"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Akufo-Addo-s-Ghana-Beyond-Aid-swallowed-by-galamsey-luxury-flights-Cathedral-hole-Spio-Garbrah-1763912"),
    Page("https://www.ghanaweb.com/GhanaHomePage/politics/Mahama-deserves-to-be-president-Spio-Garbrah-1763906"),
    Page("https://www.ghanaweb.com/GhanaHomePage/regional/Youths-in-Akrofuom-ditch-galamsey-for-farming-due-to-PERD-1764398"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Defamation-suit-Ken-Agyapong-appeals-Kweku-Baako-s-2020-win-citing-Frimpong-Boateng-report-1763282"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Frimpong-Boateng-report-Galamsey-holds-US-6bn-for-Ghana-let-s-leverage-it-Kludjeson-1763192"),

    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-cause-of-quadrupling-kidney-cases-Dr-Kenneth-Ashigbey-1763831"),
    Page("https://www.ghanaweb.com/GhanaHomePage/business/Galamsey-industry-worth-6-billion-Ghana-must-leverage-it-Kludjeson-1763195"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Ghana-is-now-a-galamsey-republic-under-Nana-Addo-and-Bawumia-MP-1763339"),
    Page("https://www.ghanaweb.com/GhanaHomePage/features/It-will-be-a-catastrophe-to-elect-Bawumia-as-president-1763714"),
    Page("https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Today-in-History-I-rejected-a-V8-vehicle-from-Chinese-Galamseyers-MP-1763495")
  )

  // Total in group 5 above is 10 + 55 = 65, so need 135 more to get 200 in that group.
  // That's the 10 pages that were collected.
  // However, there are now 100 + 135 = 235 total.
  val twoHundred = Seq(
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Aside-Chief-of-Staff-I-gave-copy-of-galamsey-report-to-CID-Frimpong-Boateng-explains-1762520"),
    Page("https://ghanaweb.com/GhanaHomePage/regional/Curbing-open-defecation-Residents-appeal-for-completion-of-toilet-facility-at-Denkyira-Kyekyewere-1763006"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Geological-investigation-is-crucial-to-fighting-galamsey-Minerals-Commission-1762736"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/I-m-ashamed-to-be-a-Ghanaian-under-this-reckless-Nana-Addo-Bawumia-government-MP-1762796"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Minerals-Commission-underlines-four-root-causes-of-galamsey-1762997"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Today-at-the-newsstands-May-8-2023-1762622"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Akufo-Addo-s-promise-to-fight-galamsey-was-a-hoax-Former-Ambassador-1762493"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/We-ll-turn-the-whole-Ghana-into-a-desert-Galamseyer-tells-Akufo-Addo-1762241"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Akufo-Addo-will-be-a-miserable-retiree-NDC-man-1761770"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Gabby-is-cause-of-60-of-Akufo-Addo-government-s-headaches-Kwaku-Annan-1761812"),
    Page("https://ghanaweb.com/GhanaHomePage/features/It-s-about-time-capital-punishment-was-introduced-in-Ghana-1762001"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/OSP-must-investigate-activities-of-Operation-Vanguard-too-ASEPA-1761857"),
    Page("https://ghanaweb.com/GhanaHomePage/regional/Uncovered-galamsey-pits-spreading-mosquitoes-in-Upper-Denkyira-East-Municipality-1761956"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/7-things-in-Akufo-Addo-s-letter-to-Al-Jazeera-that-Martin-Amidu-makes-nonsense-of-1761386"),
    Page("https://ghanaweb.com/GhanaHomePage/features/Galamsey-fight-Prof-Frimpong-Boateng-versus-the-Jubilee-House-1761509"),
    Page("https://ghanaweb.com/GhanaHomePage/business/Galamsey-fight-Stop-the-use-of-mercury-in-gold-mining-Richard-Ofori-Atta-1761356"),
    Page("https://ghanaweb.com/GhanaHomePage/business/Galamsey-report-I-will-honour-Special-Prosecutor-s-invitation-Frimpong-Boateng-1761089"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-report-I-will-honour-Special-Prosecutor-s-invitation-Prof-Frimpong-Boateng-1761086"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/It-s-been-2-years-since-I-left-why-would-I-leak-galamsey-report-Frimpong-Boateng-1761716"),
    Page("https://ghanaweb.com/GhanaHomePage/features/President-Akufo-Addo-advises-others-well-but-does-next-to-nothing-himself-Part-ll-1761350"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/State-Prosecutors-close-evidence-after-parading-11-witnesses-in-Aisha-Huang-trial-1761110"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Today-at-the-newsstands-May-5-2023-1761293"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Today-in-History-Ghana-is-sick-the-nonsense-must-stop-Lawrence-Tetteh-1761368"),
    Page("https://ghanaweb.com/GhanaHomePage/features/Ghanaian-politics-A-good-soil-for-good-men-and-women-1760765"),
    Page("https://ghanaweb.com/GhanaHomePage/features/Ghana-s-problem-is-the-Parliament-1760636"),
    Page("https://ghanaweb.com/GhanaHomePage/crime/GIS-officials-tell-court-how-Aisha-Huang-was-repatriated-1760453"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/How-do-we-deal-with-social-media-excesses-in-election-seasons-Afenyi-Dadzie-asks-1760285"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Kissi-Agyebeng-invites-Prof-Frimpong-Boateng-for-investigations-into-galamsey-report-1760894"),
    Page("https://ghanaweb.com/GhanaHomePage/regional/Two-minors-who-died-in-an-abandoned-mining-pit-buried-1760396"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/34-forest-reserves-under-threat-to-illegal-mining-Forestry-Commission-1759517"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Aisha-Huang-convicted-after-changing-her-plea-to-guilty-on-immigration-offense-1760078"),
    Page("https://ghanaweb.com/GhanaHomePage/regional/Chiefs-can-write-a-better-report-about-galamsey-menace-in-Ghana-Esiama-Chief-1760141"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Clement-Apaak-exposes-NPP-for-taking-credit-for-the-FIFA-project-in-the-Upper-East-Region-1759979"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Editorial-by-The-Chronicle-Stemming-the-threat-of-galamsey-Enough-of-the-rhetoric-1760075"),
    Page("https://ghanaweb.com/GhanaHomePage/features/Ernest-Owusu-Bempah-writes-My-Second-Coup-D-etat-the-evil-machinations-of-a-dead-goat-1760192"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Freedom-of-expression-not-a-preserve-of-journalists-Gifty-Afenyi-Dadzie-1760180"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-report-You-re-deepening-the-suspicion-Kwamena-Duncan-stings-charles-Bissue-1759586"),
    Page("https://ghanaweb.com/GhanaHomePage/features/Ghana-s-problem-is-the-parliament-1759955"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Minority-will-initiate-processes-for-independent-probe-into-Gold-Mafia-documentary-Ato-Forson-1759973"),
    Page("https://ghanaweb.com/GhanaHomePage/entertainment/Rex-Omar-This-government-has-woefully-failed-except-for-Year-of-Return-programme-1759565"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Special-Prosecutor-petitioned-to-investigate-Frimpong-Boateng-s-galamsey-report-1759646"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Today-at-the-newsstands-May-3-2023-1759709"),
    Page("https://ghanaweb.com/GhanaHomePage/features/Was-Sir-John-a-greedy-bastard-by-J-J-Rawlings-perception-1759916"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/34-forest-reserves-under-threat-of-illegal-mining-Forestry-Commission-1759415"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-Fight-A-G-laments-slow-court-processes-and-demands-cooperation-from-Judiciary-1759436"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-report-Capt-Koda-didn-t-authorise-release-of-my-excavators-Asene-Akroso-MP-1759118"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/LIVESTREAMED-Lands-minister-gives-updates-on-Ghana-s-forest-reserves-galamsey-fight-1759112"),
    Page("https://ghanaweb.com/GhanaHomePage/features/President-Akufo-Addo-advises-others-well-but-does-next-to-nothing-himself-1759349"),
    Page("https://ghanaweb.com/GhanaHomePage/features/So-long-as-the-head-is-intact-it-will-be-given-a-hat-to-wear-1759505"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Today-at-the-newsstands-May-2-2023-1759004"),
    Page("https://ghanaweb.com/GhanaHomePage/regional/Two-teenagers-killed-in-galamsey-pit-at-Asante-Bekwai-1759319"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/Akufo-Addo-bused-reporters-to-his-mother-s-house-not-his-galamsey-house-at-Kyebi-Sammy-Gyamfi-alleges-1758656"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/Akufo-Addo-will-score-zero-as-protector-of-the-environment-Richard-Prah-1758557"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-report-I-ve-resolved-not-to-talk-about-that-man-NPP-MP-slams-Prof-Frimpong-Boateng-1758767"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/How-15-3-million-Heritage-Imperial-s-galamsey-judgment-against-the-State-was-set-aside-1758773"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Failed-fight-against-illegal-mining-due-to-lack-of-trust-in-mining-sector-CDD-Fellow-1758257"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-fight-Let-s-stop-the-name-calling-and-focus-on-the-solutions-Ellembelle-DCE-1758407"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-report-Let-s-not-focus-on-name-calling-Ellembelle-DCE-1758290"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-report-People-are-now-accepting-illegal-mining-due-to-its-prevalence-Ellembelle-DCE-1758305"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Kwasi-Bonzoh-hailed-for-fighting-galamsey-in-Ellembelle-District-1758416"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Parliament-must-investigate-MPs-involved-in-galamsey-Kwame-Jantuah-1758194"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/PLAYBACK-Newsfile-on-Joy-News-1758206"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Score-yourself-did-you-pass-or-fail-in-your-work-as-chairman-of-IMCIM-Prof-Frimpong-Boateng-asked-1758059"),
    Page("https://ghanaweb.com/GhanaHomePage/features/The-politicization-of-Ghana-s-fight-against-galamsey-A-threat-to-national-development-1758359"),
    Page("https://ghanaweb.com/GhanaHomePage/features/Article-71-office-holders-and-retiring-emoluments-when-ex-gratia-meets-nemo-dat-quod-non-habet-russia-ukraine-war-and-during-debt-exchange-reflections-of-a-citizen-not-a-spectator-1758296"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/It-is-our-land-we-will-destroy-it-Galamseyer-taunts-Akufo-Addo-1758218"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/I-ve-never-spoken-to-Prof-Frimpong-Boateng-in-my-life-Charles-Owusu-responds-to-galamsey-report-1757660"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Whatever-Paul-Afoko-did-to-Nana-Addo-for-him-to-take-it-on-his-brother-must-be-really-serious-Barker-Vormawor-1757732"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/Your-ignorance-and-arrogance-nauseates-me-Owusu-Bempah-to-ASEPA-boss-1757981"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Act-swiftly-on-Frimpong-Boateng-s-Galamsey-report-GII-urges-Akufo-Addo-anti-corruption-bodies-1757675"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Frimpong-Boateng-cast-me-as-a-saboteur-disloyal-lawless-person-Gabby-tells-court-1757744"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/FULL-DOCUMENT-Gabby-s-GH-10-million-defamation-suit-against-Frimpong-Boateng-1757726"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Gabby-s-GH-10m-defamation-suit-Barker-Vormawor-offers-to-represent-Frimpong-Boateng-1757729"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-fight-Akufo-Addo-must-resign-Lawyer-1757906"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-fight-Government-must-amend-mining-law-Paul-Amaning-1757945"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-report-The-state-has-given-its-blessing-for-environmental-destruction-Prof-Bokpin-1757741"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-report-You-are-speaking-out-of-bitterness-Charles-Owusu-takes-on-Frimpong-Boateng-1757777"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Gold-Mafia-Forget-Nana-Addo-his-letter-hasn-t-reached-Aljazeera-Sammy-Gyamfi-1757951"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/How-patriotic-Frimpong-Boateng-saved-Ghana-US-88m-in-judgement-debt-Ablakwa-shares-documents-1757756"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/It-will-be-scandalous-for-Akufo-Addo-to-interfere-in-galamsey-fight-Abu-Jinapor-1757690"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/It-will-be-scandalous-for-Akufo-Addo-to-interfere-in-galamsey-fight-Abu-Jinapor-1757786"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Kyebihene-challenges-Prof-Frimpong-Boateng-over-claims-of-galamsey-activities-near-the-president-s-residence-1757870"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/LIVESTREAMED-Newsfile-on-Joy-News-1757861"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/No-galamsey-in-Akufo-Addo-s-Kyebi-backyard-Palgrave-Boakye-Danquah-1758026"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/The-audio-was-doctored-Ex-NPP-executive-denies-Gabby-called-me-over-galamsey-report-1757972"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Your-report-is-bogus-lacks-substance-Miracles-Aboagye-to-Frimpong-Boateng-1757747"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/He-called-me-Ex-NPP-executive-indicts-Gabby-over-galamsey-defends-Frimpong-Boateng-1757714"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Comic-Relief-Sammy-Gyamfi-reacts-to-Akufo-Addo-s-letter-to-Al-Jazeera-1757036"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-in-Ghana-is-like-cocaine-in-Mexico-and-Colombia-it-s-a-whole-cartel-Presidential-Staffer-1756901"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/I-ve-never-spoken-to-Prof-Frimpong-Boateng-in-my-life-Charles-Owusu-responds-to-galamsey-report-1757483"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Akufo-Addo-is-a-pretender-he-has-failed-in-the-galamsey-fight-NPP-Communicator-1757372"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/Akufo-Addo-not-prepared-to-deal-with-galamsey-report-bi-partisan-committee-needed-Minority-1756961"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Akufo-Addo-s-Kyebi-garden-not-galamsey-field-Angry-chiefs-dare-Frimpong-Boateng-to-prove-claim-1756874"),
    Page("https://ghanaweb.com/GhanaHomePage/business/Cocoa-sector-not-collapsing-COCOBOD-blasts-Mahama-1757564"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/COCOBOD-slams-Mahama-over-claims-that-Ghana-s-cocoa-sector-is-collapsing-1757585"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Come-and-show-us-the-Kyebi-garden-you-reclaimed-Akufo-Addo-s-uncle-to-Frimpong-Boateng-1757033"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Gabby-s-galamsey-kingpin-client-was-sales-manager-at-Viasat-1-NDC-s-Baba-Sadiq-1757102"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-fight-Illegal-miners-to-be-made-to-sign-reclamation-bonds-EPA-Boss-1756892"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-report-Gabby-sues-Prof-Frimpong-Boateng-demands-GH-10m-in-damages-1757600"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-report-Kennedy-Agyapong-s-lawyer-accuses-Kwaku-Baako-of-committing-perjury-1757093"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-report-Up-your-game-or-resign-Kojo-Oppong-Nkrumah-told-1756871"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/I-don-t-eat-at-chop-bars-again-the-grasscutters-now-drink-galamsey-water-Alex-Segbefia-1757360"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/If-Ghana-will-collapse-it-s-because-of-NPP-and-NDC-Dr-Benjamin-Otchere-Ankrah-snaps-1756880"),
    Page("https://ghanaweb.com/GhanaHomePage/features/Is-the-green-Ghana-Project-another-chop-chop-1757354"),
    Page("https://ghanaweb.com/GhanaHomePage/business/It-will-be-scandalous-for-Akufo-Addo-to-interfere-in-galamsey-fight-Abu-Jinapor-1757249"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/Jubilee-House-now-a-crime-scene-Sammy-Gyamfi-1757069"),
    Page("https://ghanaweb.com/GhanaHomePage/regional/NDC-is-the-reason-why-government-cannot-fight-galamsey-Dennis-Miracles-1756868"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/Probe-persons-mentioned-in-Frimpong-Boateng-s-galamsey-report-Sosu-1757024"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Prof-Frimpong-Boateng-defends-his-son-s-ownership-of-mining-concessions-1757366"),
    Page("https://ghanaweb.com/GhanaHomePage/business/Responsible-mining-critical-to-avoid-sanctions-Richard-Ofori-Atta-to-African-countries-1757264"),
    Page("https://ghanaweb.com/GhanaHomePage/features/Sir-John-is-dead-and-gone-but-his-name-is-alive-in-the-galamsey-fight-and-land-grabbing-saga-1757408"),
    Page("https://ghanaweb.com/GhanaHomePage/features/The-rise-and-fall-of-Prof-Kwabena-Frimpong-Boateng-1757348"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/There-are-pastors-actively-involved-in-galamsey-Dennis-Miracles-fiscloses-1756913"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/We-will-probe-Prof-Frimpong-Boateng-galamsey-report-if-need-be-Majority-Leader-1757252"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Who-is-Prof-Kwabena-Frimpong-Boateng-outside-of-politics-galamsey-1757132"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/You-can-t-succeed-in-smearing-Nkrumah-with-galamsey-Miracles-Aboagye-1757324"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/Is-this-how-an-elderly-person-should-behave-Miracles-Aboakye-to-Frimpong-Boateng-1757060"),
    Page("https://ghanaweb.com/GhanaHomePage/features/24-Karat-reign-of-his-Majesty-Otumfuo-Osei-Tutu-II-1756352"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Akufo-Addo-has-referred-Frimpong-Boateng-report-to-CID-for-probe-Ahiagbah-alleges-1756328"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Akufo-Addo-s-Kyebi-residence-doesn-t-have-a-garden-NPP-replies-Frimpong-Boateng-1756289"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Den-of-blackmail-and-extortion-NDC-s-Baba-Sadiq-drags-Coffee-Shop-Mafia-over-Frimpong-Boateng-report-1756373"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Disregard-hungry-angry-Frimpong-Boateng-Wontumi-accuses-former-minister-of-sinister-agenda-1756325"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-fight-Kabila-fires-Kan-Dapaah-over-hollow-national-security-1756652"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-report-I-m-disappointed-in-the-Presidency-Kabila-1756241"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-Don-t-think-you-ll-succeed-just-give-up-Allotey-Jacobs-tells-Akufo-Addo-1756244"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-I-still-stand-by-my-shoot-to-kill-comment-Joe-Wise-1756202"),
    Page("https://ghanaweb.com/GhanaHomePage/business/GEA-worried-over-youth-in-galamsey-betting-1756673"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/GH-326m-allocated-for-dislodged-miners-must-be-accounted-for-Ablakwa-to-government-1756337"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/Gradually-Akufo-Addo-is-going-down-as-the-worst-president-in-history-Steve-Manteaw-on-galamsey-report-1756298"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/I-warned-against-revival-of-Komenda-Sugar-Factory-but-people-didn-t-understand-me-Kyei-Mensah-Bonsu-1756655"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Mensah-Thompson-Owusu-Bempah-clash-over-Frimpong-Boateng-s-galamsey-report-1756670"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/Nana-Addo-s-gov-t-has-destroyed-our-forest-with-galamsey-for-their-selfish-gains-Mahama-1756274"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/No-proof-that-Frimpong-Boateng-and-son-are-involved-in-galamsey-Kwesi-Pratt-rubbishes-report-1756247"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Political-will-missing-in-galamsey-fight-Veteran-anti-corruption-activist-1756286"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Prof-Frimpong-Boateng-s-report-as-needless-and-a-complete-disaster-Kwamena-Duncan-1756238"),
  )

  // However, there are now 235 + 200 = 435 total.
  val fourHundred = Seq(
    Page("https://ghanaweb.com/GhanaHomePage/pressreleases/Re-Akufo-Addo-collapsed-cocoa-sector-1756811"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/See-video-pictures-of-Akufo-Addo-s-Kyebi-residence-allegedly-destroyed-by-galamsey-1756856"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Sitting-on-stinking-Frimpong-Boateng-report-for-2-years-magnifies-Akufo-Addo-s-complicity-in-galamsey-scandal-NDC-1756235"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Three-former-appointees-of-Akufo-Addo-giving-him-sleepless-nights-1756763"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Was-he-a-mumu-in-the-cabinet-Adom-Otchere-replies-Frimpong-Boateng-1756295"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Why-didn-t-Prof-Frimpong-Boateng-submit-his-galamsey-report-to-cabinet-while-in-office-Majority-leader-asks-1756574"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/Why-should-the-NPP-take-responsibility-for-galamsey-is-my-party-chairman-the-one-supervising-it-Lawuratu-Musa-Saaka-1756739"),
    Page("https://ghanaweb.com/GhanaHomePage/business/WTO-boss-backs-just-energy-transition-for-Africa-1756346"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/We-cannot-allow-those-who-enjoyed-galamsey-with-their-side-chicks-to-go-unpunished-Sammy-Gyamfi-1756400"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/From-Flagstaff-House-to-Galamsey-House-Henry-Akoto-expresses-sadness-over-seat-of-govt-1756007"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/3-siblings-2-others-charged-over-theft-of-gold-worth-GH-1-8-million-1755866"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Akufo-Addo-has-collapsed-cocoa-sector-John-Mahama-1755506"),
    Page("https://ghanaweb.com/GhanaHomePage/business/Akufo-Addo-has-collapsed-cocoa-sector-John-Mahama-1755509"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/Akufo-Addo-was-never-determined-to-fight-illegal-mining-Sammy-Gyamfi-1755473"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Akufo-Addo-s-government-has-spent-over-GH-300-million-in-the-past-3-years-to-fight-galamsey-Suhuyini-1755884"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/Akufo-Addo-s-Jubilee-House-now-mafia-den-NDC-1755626"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/Akufo-Addo-s-galamsey-fight-scam-calculated-to-enrich-cronies-NPP-topshots-NDC-1755521"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Akufo-Addo-s-galamsey-fight-was-a-fraudulent-one-Ato-Forson-calls-for-national-probe-1755527"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Akufo-Addo-s-Kyebi-house-never-used-for-galamsey-NPP-Abuakwa-South-replies-Frimpong-Boateng-1755530"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Check-the-current-state-of-River-Pra-compared-to-7-months-ago-1755575"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/CHRAJ-to-hold-public-hearing-on-petition-to-probe-Frimpong-Boateng-s-galamsey-report-1756106"),
    Page("https://ghanaweb.com/GhanaHomePage/features/Everything-scatter-1755953"),
    Page("https://ghanaweb.com/GhanaHomePage/features/For-the-fight-against-galamsey-corruption-and-crimes-to-succeed-vote-for-Kennedy-Agyapong-1755761"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/Frimpong-Boateng-s-report-is-an-obituary-of-Akufo-Addo-s-failed-galamsey-fight-NDC-1755584"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-claims-CHRAJ-exonerates-Frimpong-Boateng-1755950"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-fight-Akufo-Addo-s-promise-to-put-his-presidency-on-the-line-was-a-figure-of-speech-Charles-Bissue-1756040"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-report-How-can-you-say-this-is-a-report-of-personal-grievances-Randy-Abbey-slams-presidency-1755779"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-report-I-spoke-to-Prof-in-2019-over-excavator-on-low-bed-vehicle-on-highway-Presidential-aide-1755542"),
    Page("https://ghanaweb.com/GhanaHomePage/business/Government-spent-over-GH-300-million-in-last-3-years-to-fight-galamsey-Suhuyini-1755893"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/IMCIM-report-Things-don-t-just-add-up-unless-Akufo-Addo-is-personally-benefiting-from-galamsey-MP-1755827"),
    Page("https://ghanaweb.com/GhanaHomePage/entertainment/John-Dumelo-urges-action-against-galamsey-to-protect-Ghana-s-cocoa-industry-and-environment-1756082"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Martin-Amidu-writes-Akufo-Addo-is-an-admitted-friend-of-Alistair-Mathias-period-1755524"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/NDC-calls-on-Special-Prosecutor-to-investigate-Al-Jazeera-money-laundering-allegations-against-Akufo-Addo-1755629"),
    Page("https://ghanaweb.com/GhanaHomePage/features/Poverty-ecocide-and-environmental-degradation-a-threat-to-our-common-home-1755914"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Suhuyini-details-how-some-government-officials-used-military-for-galamsey-protection-duties-1755596"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Three-major-arrests-made-by-the-police-between-March-and-April-2023-1755767"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Today-at-the-newsstands-April-26-2023-1755638"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Watch-Adom-Otchere-s-comment-that-earned-him-a-place-in-Frimpong-Boateng-s-letter-1755548"),
    Page("https://ghanaweb.com/GhanaHomePage/features/Presidential-galamseyers-exposed-insincere-Akufo-Addo-s-regime-to-fight-galamsey-menace-1755908"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Frimpong-Boateng-is-politically-immature-Maurice-Ampaw-1754831"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Posterity-will-not-forgive-Akufo-Addo-Gabby-s-2017-tweet-about-galamsey-comes-biting-1754849"),
    Page("https://ghanaweb.com/GhanaHomePage/features/A-letter-to-PRINPAG-on-their-silence-in-the-face-of-the-attacks-on-Kojo-Oppong-Nkrumah-over-Frimpong-Boateng-s-report-1755461"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Ban-on-all-forms-of-mining-activities-following-Frimpong-Boateng-s-report-MP-1754873"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Dafeamekpor-petitions-CHRAJ-to-probe-Prof-Frimpong-Boateng-s-galamsey-report-1755308"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Deal-with-galamsey-in-your-constituency-Frimpong-Boateng-tells-Oppong-Nkrumah-1754783"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Former-Nkwanta-MP-sold-me-the-concession-Man-whose-mining-equipment-were-burnt-1755356"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/Galamsey-Blues-Political-power-short-lived-Frimpong-Boateng-advises-Kojo-Oppong-Nkrumah-1754786"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-report-Minority-Leader-calls-for-national-probe-1754942"),
    Page("https://ghanaweb.com/GhanaHomePage/features/How-could-galamsey-stop-when-those-fighting-it-are-the-same-people-practicing-it-1755359"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/IMCIM-report-Prof-Frimpong-Boateng-shares-video-of-galamsey-site-linked-to-Oppong-Nkrumah-1755173"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/IMCIM-report-Video-of-alleged-destruction-at-galamsey-site-linked-to-Lord-Commey-pops-up-1755068"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Major-Mahama-s-name-mentioned-in-Frimpong-Boateng-s-galamsey-report-1755221"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Media-war-between-Frimpong-Boateng-and-persons-accused-needless-Lawyer-1754765"),
    Page("https://ghanaweb.com/GhanaHomePage/features/Nana-Akufo-Addo-does-not-deny-that-he-is-financial-architect-Alistair-Mathias-good-friend-1755188"),
    Page("https://ghanaweb.com/GhanaHomePage/crime/Police-confirm-arrest-of-Axim-galamsey-kingpin-Kwame-Ato-Ani-three-others-1754822"),
    Page("https://ghanaweb.com/GhanaHomePage/business/Suspend-the-issuance-of-new-mining-licences-WACAM-1755110"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/The-3-NPP-bigwigs-at-each-other-s-throats-over-galamsey-1755041"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/The-idea-Akufo-Addo-didn-t-know-about-galamsey-report-is-a-joke-NPP-member-1755272"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Pray-for-Prof-Frimpong-Boateng-against-forces-of-evil-Clement-Apaak-1754834"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/CID-too-compromised-to-tackle-galamsey-investigation-Political-activist-1754750"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Government-s-sudden-interest-in-galamsey-report-is-PR-not-leadership-Political-Activist-1754744"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/I-don-t-think-you-have-retrograde-amnesia-Frimpong-Boateng-drags-Gabby-Otchere-Darko-1754417"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Prepare-for-a-legal-showdown-Informer-Newspaper-Editor-to-Prof-Frimpong-Boateng-1754390"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Prof-Frimpong-Boateng-advises-son-Kojo-Oppong-Nkrumah-1754609"),
    Page("https://ghanaweb.com/GhanaHomePage/features/Prof-Frimpong-Boateng-s-leaked-report-on-IMCIM-the-last-blow-to-send-NPP-to-opposition-1754447"),
    Page("https://ghanaweb.com/GhanaHomePage/regional/Prof-Quarm-cannot-run-away-from-galamsey-report-GNASSM-Ashanti-spills-more-secrets-1754702"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Saboteurs-within-Akufo-Addo-s-government-made-sure-he-lost-galamsey-fight-Kawor-1754435"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/The-content-of-Prof-Frimpong-Boateng-s-galamsey-report-is-not-the-whole-truth-Dr-Steve-Manteaw-1754555"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/I-don-t-even-have-a-single-concession-he-s-only-tarnishing-my-image-Former-Manso-Nkwanta-MP-1754096"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Where-was-security-Sam-George-on-allegations-of-NPP-youth-organizer-digging-Akufo-Addo-s-garden-for-gold-1754180"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Fighting-galamsey-is-everlasting-and-almost-impossible-just-like-corruption-ILAPI-boss-1754285"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/IMCIM-report-How-an-NPP-youth-organizer-used-Akufo-Addo-s-garden-for-galamsey-1754165"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/It-is-a-catalogue-of-personal-claims-and-grievances-Presidency-discounts-Frimpong-Boateng-s-galamsey-report-1754039"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Jubilee-House-labels-Prof-Frimpong-Boateng-s-32-paged-galamsey-report-as-hearsay-1754048"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/There-is-a-chance-the-report-of-Prof-Frimpong-Boateng-was-withheld-ILAPI-Boss-1754012"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/What-Gabby-said-about-galamsey-fight-in-2017-1754105"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Which-law-school-taught-you-to-call-and-question-a-minister-on-phone-Sammy-Gyamfi-asks-influence-peddling-Gabby-1754042"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Silly-Frimpong-Boateng-reported-me-to-the-president-to-do-what-Gabby-fumes-1753568"),
    Page("https://ghanaweb.com/GhanaHomePage/regional/Boundary-Commission-coordinator-visits-Dollar-Power-galamsey-community-1753919"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Chiefs-who-support-galamsey-should-be-destooled-Akyempimhene-of-Suhum-1753589"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Come-out-with-the-truth-you-are-unclean-too-Charles-Bissue-dares-Frimpong-Boateng-1753766"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Frimpong-Boateng-s-report-contains-catalogue-of-grievances-and-hearsay-Presidency-1753751"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Frimpong-Boateng-s-report-not-surprising-Small-Scale-Miners-1753661"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/If-we-were-a-serious-country-we-would-have-acted-in-ways-that-help-us-to-address-galamsey-Dr-Manteaw-1753910"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/I-ve-nothing-to-gain-from-sullying-Frimpong-Boateng-s-reputation-Oppong-Nkrumah-1753553"),
    Page("https://ghanaweb.com/GhanaHomePage/crime/Kwame-Ato-Asare-Ani-and-his-accomplices-finally-arrested-in-Enchi-1753763"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Professor-Frimpong-Boateng-makes-wild-allegations-against-NDC-members-in-galamsey-report-1753769"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Why-blame-me-after-telling-police-media-about-500-missing-excavators-Oppong-Nkrumah-1753610"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/I-visited-galamsey-sites-and-I-became-speechless-John-Dumelo-1753463"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/All-the-big-names-listed-as-galamsey-culprits-in-Prof-Frimpong-s-report-1753466"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/Frimpong-Boateng-names-presidential-galamseyers-in-explosive-report-1752914"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/How-Oppong-Nkrumah-hatched-plot-to-bring-me-down-over-galamsey-fight-Frimpong-Boateng-details-in-report-1752989"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/How-we-saved-Akufo-Addo-s-Kyebi-garden-from-galamsey-Frimpong-Boateng-details-1752983"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/I-am-utterly-disappointed-but-I-forgive-him-Oppong-Nkrumah-replies-Prof-Frimpong-Boateng-1753394"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Part-II-of-Frimpong-Boateng-s-galamsey-expos-is-more-disturbing-Kevin-Taylor-hints-1753019"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Please-leave-me-out-of-your-fights-Oppong-Nkrumah-to-Frimpong-Boateng-1753412"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Prove-that-I-m-into-galamsey-protected-people-in-it-Lord-Commey-challenges-Prof-Frimpong-Boateng-1753367"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/The-exact-things-Sir-John-was-doing-that-earned-him-the-greatest-danger-to-forests-tag-1753169"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/You-twisted-my-4-minute-call-on-behalf-of-a-client-as-interference-Gabby-replies-Frimpong-Boateng-1752977"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Greatest-danger-to-forests-of-Ghana-was-Sir-John-Frimpong-Boateng-report-1753103"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/He-who-alleges-must-prove-NPP-Bigwig-challenges-Frimpong-Boateng-over-galamsey-report-1753340"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Lord-Commey-Nii-Teiko-ex-NPP-MP-NDC-MP-cited-in-Frimpong-Boateng-s-galamsey-report-1752848"),
    Page("https://ghanaweb.com/GhanaHomePage/crime/Two-other-Chinese-nationals-charged-with-Aisha-Huang-s-son-convicted-fined-GHc24K-1752242"),
    Page("https://ghanaweb.com/GhanaHomePage/crime/Attacks-on-police-rising-due-to-loss-of-public-confidence-Former-CID-Boss-1751546"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Attacks-on-Police-Commanders-and-supervisors-must-up-their-game-Ex-CID-boss-1751549"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Missing-excavators-Osafo-Maafo-reportedly-told-people-to-fight-Frimpong-Boateng-over-Ekow-Ewusi-s-arrest-1752179"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Aisha-Huang-re-entered-Ghana-through-Aflao-Port-claimed-she-d-missed-her-husband-Witness-1750877"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/How-galamsey-destroyed-part-of-garden-at-Akufo-Addo-s-Kyebi-residence-Report-1751024"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/An-eyewitness-account-of-what-led-to-burning-of-suspected-robbers-at-Moseaso-1750682"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/World-Bank-will-withdraw-support-if-we-politicize-fight-against-galamsey-GLRSSMP-1750232"),
    Page("https://ghanaweb.com/GhanaHomePage/business/World-Bank-will-withdraw-support-if-we-politicize-fight-against-galamsey-GLRSSMP-1750235"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/NPP-is-a-no-action-talk-only-party-Mahama-jabs-1750118"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Small-Scale-Miners-Association-accuses-government-of-politicizing-fight-against-galamsey-1749122"),
    Page("https://ghanaweb.com/GhanaHomePage/features/Is-it-always-prudent-to-back-a-winning-horse-1748486"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Our-water-body-has-been-contaminated-for-six-years-due-to-galamsey-Assemblyman-1748252"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Akufo-Addo-s-vow-to-risk-presidency-in-galamsey-fight-lacked-credibility-Jantuah-1747778"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/IGP-must-resign-for-failing-in-galamsey-fight-Jantuah-1747718"),
    Page("https://ghanaweb.com/GhanaHomePage/business/Gold-Mafia-Deafening-official-silence-in-Ghana-even-after-third-episode-1746587"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/How-a-former-galamseyer-risked-it-all-to-cross-the-Libyan-desert-to-seek-asylum-in-Italy-1746716"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Mireku-Duker-commissions-Afransie-Community-Mining-Scheme-1746611"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/From-Ghana-to-Germany-Tracking-down-the-owner-of-a-lost-wallet-1746338"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Videos-that-led-social-media-trends-in-the-past-week-1745912"),
    Page("https://ghanaweb.com/GhanaHomePage/regional/Galamsey-fight-is-a-shared-responsibility-Mireku-Duker-to-government-communicators-1745429"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Aisha-Huang-s-passports-bear-different-names-dates-of-birth-GIS-Officer-to-court-1744556"),
    Page("https://ghanaweb.com/GhanaHomePage/SportsArchive/Dunkwa-on-Offin-youth-resource-center-to-be-completed-by-end-of-May-1745048"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-fight-Ghana-Armed-Forces-touts-achievements-of-Operation-Halt-1745045"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/I-have-asked-my-small-boy-to-turn-himself-in-A-Plus-on-wanted-Axim-galamsey-kingpin-1744634"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Today-at-the-newsstands-April-6-2023-1744700"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Gangsterism-terrorism-and-rape-Reported-lifestyle-of-22-year-old-galamsey-gang-leader-1743956"),
    Page("https://ghanaweb.com/GhanaHomePage/entertainment/Ghana-police-is-a-criminal-organisation-Kwame-A-Plus-reacts-to-galamseyers-assaulting-a-policeman-1743782"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Ghana-police-is-a-criminal-organisation-Kwame-A-Plus-reacts-to-galamseyers-assaulting-a-policeman-1743785"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/I-am-putting-up-a-hotel-with-86-rooms-in-Axim-22-year-old-galamsey-kingpin-1743920"),
    Page("https://ghanaweb.com/GhanaHomePage/entertainment/I-respect-Akufo-Addo-but-I-won-t-massage-his-balls-A-Plus-1743992"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Mireku-Duker-commissions-Afransie-Community-Mining-Scheme-1744466"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Police-have-arrested-innocent-citizens-Axim-galamsey-leader-speaks-from-hideout-1743965"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Police-officer-who-knelt-and-begged-Axim-gang-leader-is-wise-Ex-police-capo-1743929"),
    Page("https://ghanaweb.com/GhanaHomePage/audio/Quarme-Zaggy-bags-two-nominations-at-Ghana-Music-Awards-Europe-2023-1744154"),
    Page("https://ghanaweb.com/GhanaHomePage/regional/Schools-in-Axim-weren-t-closed-down-by-Kwame-Ato-Asare-Nzema-East-MCE-1744349"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/The-image-of-Ghana-Police-under-Dr-Dampare-is-not-positive-Lecturer-1744061"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/2-recent-times-uniformed-policemen-have-been-caught-in-awkward-criminal-situations-1743377"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Another-video-of-Axim-galamsey-gang-leader-molesting-man-in-camouflage-pops-up-1743539"),
    Page("https://ghanaweb.com/GhanaHomePage/crime/Axim-gang-leader-I-ve-refused-to-turn-myself-in-because-I-don-t-trust-the-police-1743152"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Galamsey-fight-is-a-shared-responsibility-Mireku-Duker-to-govt-Communicators-1743755"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/I-have-been-paying-chop-money-to-the-police-Wanted-Axim-galamsey-gang-leader-1743317"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/My-gun-was-given-to-me-by-the-police-for-personal-protection-Wanted-galamseyer-reveals-1743365"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Police-after-me-because-of-GH-100-000-booty-I-confiscated-Wanted-galamseyer-1743236"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Wanted-galamseyer-once-ordered-Axim-schools-to-close-over-his-missing-mobile-phone-MCE-reveals-1743242"),
    Page("https://ghanaweb.com/GhanaHomePage/regional/BMA-stops-businessman-from-dredging-Oda-River-1743017"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/I-am-an-informant-not-a-robber-Leader-of-galamsey-gang-declared-wanted-by-police-speaks-from-hideout-1742501"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Police-gun-down-notorious-galamsey-site-robber-1742885"),
    Page("https://ghanaweb.com/GhanaHomePage/features/Beware-Asanteman-task-force-1742411"),
    Page("https://ghanaweb.com/GhanaHomePage/features/Rallying-support-for-Dr-Kwabena-Duffour-for-NDC-flag-bearer-position-1742348"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Watch-how-police-officers-begged-for-their-lives-in-the-hands-of-galamsey-boys-1742174"),
    Page("https://ghanaweb.com/GhanaHomePage/audio/Second-Ghana-Music-Awards-Europe-nominees-revealed-1741805"),
    Page("https://ghanaweb.com/GhanaHomePage/regional/Galamsey-fight-Atwima-Nwabiagya-South-Assembly-sensitizes-small-scale-miners-1741571"),
    Page("https://ghanaweb.com/GhanaHomePage/regional/Expose-financiers-of-illegal-mining-in-Ashanti-Region-Otumfuo-declares-1740929"),
    Page("https://ghanaweb.com/GhanaHomePage/regional/20-year-old-man-dies-after-faling-into-galamsey-pit-1738865"),
    Page("https://ghanaweb.com/GhanaHomePage/business/Otumfuo-Gold-Coin-project-Asanteman-to-institute-taskforce-to-combat-galamsey-1738304"),
    Page("https://ghanaweb.com/GhanaHomePage/crime/12-Chinese-nationals-in-court-over-galamsey-1738079"),
    Page("https://ghanaweb.com/GhanaHomePage/business/Gold-Mafia-40m-of-Ghana-s-gold-is-washed-every-month-through-money-laundering-1737938"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Watch-as-gold-smuggler-washes-40m-of-Ghana-s-gold-every-month-1737896"),
    Page("https://ghanaweb.com/GhanaHomePage/crime/You-have-been-in-this-court-before-Judge-recognises-ex-convict-gives-him-36-months-1737161"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/George-Krobea-Asante-slams-NDC-for-undermining-galamsey-fight-1735961"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/I-wish-Prof-Frimpong-Boateng-s-galamsey-allegation-investigation-was-done-publicly-Pratt-1735967"),
    Page("https://ghanaweb.com/GhanaHomePage/business/Illegal-mining-poses-threat-to-Otumfuo-Commemorative-Gold-Coin-project-Group-1736282"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/OSP-CHRAJ-should-investigate-Frimpong-Boateng-s-Jubilee-House-galamsey-allegations-not-CID-MP-1735217"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Presidency-galamsey-saga-Akufo-Addo-is-the-professor-of-cover-ups-Bernard-Mornah-1735634"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Akufo-Addo-s-directive-for-CID-s-probe-into-Jubilee-House-galamsey-suspicious-Apaak-1734443"),
    Page("https://ghanaweb.com/GhanaHomePage/regional/Kade-Chief-calls-on-IGP-to-deal-with-Police-Commander-over-alleged-involvement-in-galamsey-1734572"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Police-declared-Prof-Frimpong-Boateng-suspect-in-galamsey-investigations-twice-Bissiw-alleges-1734920"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Adansi-Asokwa-KNUST-students-procure-oil-palm-processing-mill-for-Nyankumasu-community-1733750"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Akufo-Addo-sanctions-CID-to-probe-Prof-Frimpong-Boateng-s-Jubilee-House-galamsey-allegation-1734116"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/CID-invites-Prof-Frimpong-Boateng-over-Jubilee-House-galamsey-allegations-1734176"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Today-at-the-newsstands-March-20-2023-1733837"),
    Page("https://ghanaweb.com/GhanaHomePage/features/What-do-Ghanaians-want-from-the-NDC-Dr-Kwabena-Duffuor-1734005"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Could-there-be-a-nexus-between-Gold-for-oil-Frimpong-Boateng-s-galamsey-allegations-Apaak-1733264"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Illegal-miners-attack-mining-company-burn-12-vehicles-1733036"),
    Page("https://ghanaweb.com/GhanaHomePage/politics/Stop-joining-forces-with-immigrants-to-destroy-our-lands-waters-Minority-warns-government-1732979"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Times-Anas-Aremeyaw-Anas-character-work-were-questioned-1733111"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/You-re-part-of-the-problem-comment-Presidential-staffer-drags-Kweku-Baako-after-Anas-court-loss-1732931"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Branded-vehicle-of-the-Asanteman-Task-Force-Against-Illegal-Mining-sighted-1732646"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Govt-officials-neck-deep-in-galamsey-destruction-of-Ghana-s-lands-Rashid-Pelpuo-calls-out-Akufo-Addo-1732397"),
    Page("https://ghanaweb.com/GhanaHomePage/features/It-s-only-in-Ghana-that-Anas-Aremeyaw-Anas-is-a-hero-1732736"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Minority-demands-probe-into-Frimpong-Boateng-s-Jubilee-House-galamsey-allegation-1732301"),
    Page("https://ghanaweb.com/GhanaHomePage/regional/Protect-water-bodies-to-avoid-water-importation-Janet-Atebiya-1732562"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Editorial-by-Ghanaian-Times-Preventing-future-water-scarcity-in-Ghana-and-Cote-d-Ivoire-1732118"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/NPP-Akufo-Addo-Bawumia-must-apologize-to-Adu-Boahen-Ken-Agyapong-after-Anas-ruling-1731743"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Charles-Bissue-tackles-Prof-Frimpong-Boateng-over-500-missing-galamsey-excavators-1731068"),
    Page("https://ghanaweb.com/GhanaHomePage/regional/Fair-Trade-National-Platforms-call-for-favourable-cocoa-prices-1731506"),
    Page("https://ghanaweb.com/GhanaHomePage/regional/Give-us-licenses-to-operate-if-you-cannot-stop-galamsey-Chiefs-and-residents-of-Amansie-1730975"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/NPP-officials-took-over-people-s-properties-in-the-name-of-anti-galamsey-Kojo-Peprah-1730957"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Be-bold-to-probe-galamsey-at-presidency-even-if-Nana-Addo-Bawumia-are-involved-OSP-told-1730387"),
    Page("https://ghanaweb.com/GhanaHomePage/business/Galamsey-Government-takes-steps-to-resolve-transboundary-water-pollution-1730783"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Ghana-Ivory-Coast-commit-to-saving-transboundary-waterbodies-affected-by-galamsey-activities-1730768"),
    Page("https://ghanaweb.com/GhanaHomePage/business/People-in-government-including-Jubilee-House-are-involved-in-galamsey-Dr-Frimpong-Boateng-1729715"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Charles-Bissue-s-suit-Court-orders-OSP-to-file-Statement-of-Case-within-14-days-1729943"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/Clement-Apaak-calls-for-an-investigation-into-Prof-Boateng-s-claims-NPP-bigwigs-are-involved-in-galamsey-1729622"),
    Page("https://ghanaweb.com/GhanaHomePage/NewsArchive/I-was-removed-to-make-way-for-unfettered-illegal-mining-Prof-Frimpong-Boateng-1729931"),
    Page("https://ghanaweb.com/GhanaHomePage/features/If-Ghana-was-a-democracy-the-fate-of-Ofori-Atta-1729754"),
    Page("https://ghanaweb.com/GhanaHomePage/features/When-shall-you-wise-up-o-ye-Ghanaian-or-African-1729652")
  )

  def apply(): Corpus = {
    val pages = fourHundred // ++ twoHundred // ++ original ++ extended

    new Corpus(pages)
  }
}
